
version: '3'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: simpsons_dw
    ports:
      - "5432:5432"

  streamlit:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - postgres
